### PR TITLE
OpenFOAM 9 and dev support implemented

### PR DESCRIPTION
**Pull request by kahilah**
Present update adds support for OpenFOAM 9 and dev. Compilation is tested successfully. 

However, there are still certain streamlining in general I'm planning to do and will continue developing my of-dev branch in my fork. We can communicate here regarding those actions as well depending when you're ready to merge. 

See e.g. `OFdev_update.txt` to see some basic things that required modification in the new OF-9/dev update.

-HK

### CODE REVIEW

**Comment by moreff** [comment]
Thanks!
I need to do some tests first. And then I think I will clone the current main branch to a new separate OpenFOAM 8 branch and merge your changes.

Can you please also synchronize your fork with the main branch? Try using git rebase. For some reason, GitHub is unable to rebase your commits automatically, so the commit history will be a bit messy after a plain merge, like with your previous pull request.

**Comment by blttkgl** [comment]
Just a friendly reminder that in the next 3-4 months OpenFOAM will keep pushing new commits to the OpenFOAM-9 repository, and will update the Ubuntu package releases with these new updates. So DLBFoam_v9 might not compile on OpenFOAM-9 due to minor changes in couple of months. My suggestion is to go the other way: keep main as OpenFOAM-8 (stable) release, and create a branch for OpenFOAM-9. Once they stop pushing updates and bugfixes in fall you could swap main with v9.

Bulut

**Comment by kahilah** [comment]
@moreff Yeah, sure, test it indeed!

@blttkgl Indeed there will be updates but I have been using the dev version quite some time due to many useful features so I'm really recommending to go with the 9/dev. Whether it is a separate branch for now or in main...doesn't really matter.

I'll try the rebasing today.

**Comment by kahilah** [comment]
@moreff does it show some conflicts still? I fetched and merged your accepted merge from earlier so at least all looks good to me now?

If it still shows some issues I could merge my dev branch with my main, rebase it once again and then try with a new pull request.

**Comment by moreff** [comment]
@kahilah GitHub still says "This branch cannot be rebased due to conflicts"

**Comment by kahilah** [comment]
Ok, now I did git reset with the soft argument which should have cleared any conflict in any individual commit...Let me know did it help!

The problem with this is that I had to neglect some commits which were showing conflicts in rebasing and unfortunately even rebase --skip didn't solve thone but kind of cumulated the issues. Luckily the commits were pretty dummy back-ups because I was developing on multiple machines at a time so don't worry about "lost comments" or anything.

**Comment by mahgadalla** [comment]
Current pull request was merged locally and compiled STANDALONE for OpenFOAM-9 (switched from dev in Allwmake). Unittests run successfully. All tutorials run successfully. No issues were noted.

@moreff OpenFOAM-9 needs to be allowed for chemFoam tutorial (Allrun)

I kindly agree with @blttkgl suggestion: keeping OF8 version in main branch, and merge current pull request into OF9 branch

Awaiting further comments from others in case any!

**Comment by mahgadalla** [comment]
Just to keep the discussion updated, @moreff noted a bug in tutorial chemFoam, resulting in using standard ODE with empty reactions and no pyJac. The bug was runtime, no errors thrown, but no ignition occured in the cell. Issue fixed in 38637f8099ef74369922983cb049828e2be551aa

**Comment by drhcelik** [comment]
It doesn't compile on Triton, I will figure it out. It is probably related to some different path definitions of Triton.

**Pull request merged**
