### PR TITLE
V1.1 OF_dev update

### PR DESCRIPTION
**Pull request by blttkgl**
This pull request introduces updates to make DLBFoam compatible with the latest dev (commit ID 53dc33d25).

Some remarks:

- Unfortunately the latest dev introduces some changes the main code which needs to be reverted. See the patch file included in the repository. Main OpenFOAM-dev should be updated + recompiled with the changes that the patch includes for now.
- The dynamic compilation of loadBalanced_pyJac chemistry model currently is not working, which I'm hoping @moreff  should be able to fix
- I opened the pull request over the v1.1_OF10_dev repository, so please consider making a copy of this branch before merging my changes.

### CODE REVIEW

**Review by moreff — APPROVED** [review]

**Comment by moreff** [comment]
The dynamic compilation will be fixed in the upcoming commit to the v1.1_OFdev branch

**Comment by moreff** [comment]
@blttkgl Ok, I didn't notice this, but your fork of the repository does not have the latest commits from this repository.
I thought GitHub would warn about this on the pull request page.
So there are some conflicting commits now and the code does not compile.
I will fix them.

But in the future please make sure that your fork is synchronized with the parent repository before making the pull request

**Comment by blttkgl** [comment]
Aha, interesting. I must’ve based off of a forked branch that was not updated with your recent changes, apologies. If you revert the merge I can sort it out on my end too.

**Comment by moreff** [comment]
It's ok, I resolved it now

**Pull request merged**
